version: "3.5"
services:
# --- TORRENT CLIENT ---
  transmission:
    image: linuxserver/transmission
    container_name: transmission
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - TRANSMISSION_WEB_HOME=/combustion-release/ #optional
    volumes:
      - ./transmission:/config
      - ${DLDIR}:/downloads
      - ${DLDIR}/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
# --- TORRENT INDEXER ---
  jackett:
    image: linuxserver/jackett
    container_name: jackett
    restart: unless-stopped
    ports:
      - 9117:9117
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    volumes:
      - ./jackett:/config
      - /etc/localtime:/etc/localtime:ro
# --- TV SHOW MANAGER ---
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    restart: unless-stopped
    ports:
      - 8989:8989
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ./sonarr:/config
      - ${DLDIR}/completed:/downloads/completed
      - ${TVDIR}:/tv
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - jackett
      - transmission

networks:
  default:
    external:
      name: ${NETWORK}

